# Property Price Prediction

Here, We will create a linear model on Property price dataset. It is historical database of properties, based on which we will create a model.

In [1]:
import pandas as pd

In [39]:
prop=pd.read_csv("PROPERTYPRICE.CSV")

In [14]:

#pd.set_option('display.max_columns',None)
#pd.set_option('display.max_rows',None)

In [3]:
prop.iloc[:,0:10].describe(include='all')

,Id,Building_Class,Zoning_Class,Lot_Extent,Lot_Size,Road_Type,Lane_Type,Property_Shape,Land_Outline,Utility_Type
count,1459.000000,1459.000000,1459,1200.000000,1459.000000,1459,91,1459,1459,1459
unique,NaN,NaN,5,NaN,NaN,2,2,4,4,2
top,NaN,NaN,RLD,NaN,NaN,Paved,Grvl,Reg,Lvl,AllPub
freq,NaN,NaN,1150,NaN,NaN,1453,50,924,1310,1458
mean,730.000000,56.922550,NaN,70.045833,10517.225497,NaN,NaN,NaN,NaN,NaN
std,421.321334,42.304033,NaN,24.294456,9984.675721,NaN,NaN,NaN,NaN,NaN
min,1.000000,20.000000,NaN,21.000000,1300.000000,NaN,NaN,NaN,NaN,NaN
25%,365.500000,20.000000,NaN,59.000000,7549.000000,NaN,NaN,NaN,NaN,NaN
50%,730.000000,50.000000,NaN,69.000000,9477.000000,NaN,NaN,NaN,NaN,NaN
75%,1094.500000,70.000000,NaN,80.000000,11603.000000,NaN,NaN,NaN,NaN,NaN
max,1459.000000,190.000000,NaN,313.000000,215245.000000,NaN,NaN,NaN,NaN,NaN

We will drop unnecessary and redundant variables(coulumns).

In [40]:
prop.drop(["Id","Lane_Type","Fireplace_Quality","Pool_Quality","Fence_Quality","Miscellaneous_Feature"],axis=1,inplace=True)

In [33]:
prop.shape

(1459, 75)

In [34]:
prop.describe(include='all')

,Building_Class,Zoning_Class,Lot_Extent,Lot_Size,Road_Type,Property_Shape,Land_Outline,Utility_Type,Lot_Configuration,Property_Slope,Neighborhood,Condition1,Condition2,House_Type,House_Design,Overall_Material,House_Condition,Construction_Year,Remodel_Year,Roof_Design,Roof_Quality,Exterior1st,Exterior2nd,Brick_Veneer_Type,Brick_Veneer_Area,Exterior_Material,Exterior_Condition,Foundation_Type,Basement_Height,Basement_Condition,Exposure_Level,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,Total_Basement_Area,Heating_Type,Heating_Quality,Air_Conditioning,Electrical_System,First_Floor_Area,Second_Floor_Area,LowQualFinSF,Grade_Living_Area,Underground_Full_Bathroom,Underground_Half_Bathroom,Full_Bathroom_Above_Grade,Half_Bathroom_Above_Grade,Bedroom_Above_Grade,Kitchen_Above_Grade,Kitchen_Quality,Rooms_Above_Grade,Functional_Rate,Fireplaces,Garage,Garage_Built_Year,Garage_Finish_Year,Garage_Size,Garage_Area,Garage_Quality,Garage_Condition,Pavedd_Drive,W_Deck_Area,Open_Lobby_Area,Enclosed_Lobby_Area,Three_Season_Lobby_Area,Screen_Lobby_Area,Pool_Area,Miscellaneous_Value,Month_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price
count,1459.000000,1459,1200.000000,1459.000000,1459,1459,1459,1459,1459,1459,1459,1459,1459,1459,1459,1459.000000,1459.000000,1459.000000,1459.000000,1459,1459,1459,1459,1451,1451.00000,1459,1459,1459,1422,1422,1421,1422,1459.000000,1421,1459.000000,1459.000000,1459.000000,1459,1459,1459,1458,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459,1459.000000,1459,1459.000000,1378,1378.000000,1378,1459.000000,1459.000000,1378,1378,1459,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459,1459,1459.000000
unique,NaN,5,NaN,NaN,2,4,4,2,5,3,25,9,8,5,8,NaN,NaN,NaN,NaN,6,8,15,16,4,NaN,4,5,6,4,4,4,6,NaN,6,NaN,NaN,NaN,6,5,2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,8,NaN,7,NaN,3,NaN,NaN,5,5,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,6,NaN
top,NaN,RLD,NaN,NaN,Paved,Reg,Lvl,AllPub,I,GS,NAmes,Norm,Norm,1Fam,1Story,NaN,NaN,NaN,NaN,Gable,SS,VinylSd,VinylSd,None,NaN,TA,TA,PC,TA,TA,No,Unf,NaN,Unf,NaN,NaN,NaN,GasA,Ex,Y,SBrkr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TA,NaN,TF,NaN,Attchd,NaN,Unf,NaN,NaN,TA,TA,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WD,Normal,NaN
freq,NaN,1150,NaN,NaN,1453,924,1310,1458,1051,1381,225,1259,1444,1219,725,NaN,NaN,NaN,NaN,1140,1433,515,504,863,NaN,906,1281,647,648,1310,952,430,NaN,1256,NaN,NaN,NaN,1427,741,1364,1333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,734,NaN,1359,NaN,869,NaN,605,NaN,NaN,1310,1325,1339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1266,1197,NaN
mean,56.922550,NaN,70.045833,10517.225497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.100069,5.575051,1971.272104,1984.879369,NaN,NaN,NaN,NaN,NaN,103.75672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,443.374914,NaN,46.382454,567.535984,1057.293352,NaN,NaN,NaN,NaN,1162.562714,347.230295,5.848526,1515.641535,0.424949,0.057574,1.565456,0.382454,2.866347,1.046607,NaN,6.518163,NaN,0.613434,NaN,1978.515965,NaN,1.767649,470.934787,NaN,NaN,NaN,93.015667,47.811902,24.580227,3.411926,15.071282,2.760795,43.518849,6.322138,2007.815627,NaN,NaN,180944.102810
std,42.304033,NaN,24.294456,9984.675721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.383171,1.113125,30.212814,20.645927,NaN,NaN,NaN,NaN,NaN,181.10815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,456.142186,NaN,161.248500,441.874057,438.824912,NaN,NaN,NaN,NaN,386.712553,436.583480,48.639512,525.616607,0.518870,0.238830,0.550906,0.502798,0.816050,0.220410,NaN,1.625894,NaN,0.644687,NaN,24.696004,NaN,0.747301,210.668787,NaN,NaN,NaN,124.796682,67.467586,61.353507,29.327247,55.775138,40.191018,496.291826,2.704540,1.328542,NaN,NaN,79464.918335
min,20.000000,NaN,21.000000,1300.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1872.000000,1950.000000,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,2.000000,NaN,0.000000,NaN,1900.000000,NaN,0.000000,-129.369350,NaN,NaN,NaN,-338.112031,-187.149958,-164.807386,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,NaN,NaN,34900.000000
25%,20.000000,NaN,59.000000,7549.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,5.000000,1954.000000,1967.000000,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,223.500000,795.500000,NaN,NaN,NaN,NaN,882.000000,0.000000,0.000000,1129.000000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,NaN,5.000000,NaN,0.000000,NaN,1961.000000,NaN,1.000000,329.290489,NaN,NaN,NaN,9.656026,1.843186,-16.807302,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,NaN,NaN,129950.000000
50%,50.000000,NaN,69.000000,9477.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,5.000000,1973.000000,1994.000000,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,383.000000,NaN,0.000000,479.000000,991.000000,NaN,NaN,NaN,NaN,1086.000000,0.000000,0.000000,1464.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,NaN,6.000000,NaN,1.000000,NaN,1980.000000,NaN,2.000000,471.028116,NaN,NaN,NaN,92.803628,46.837919,25.026953,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,NaN,NaN,163000.000000
75%,70.000000,NaN,80.000000,11603.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,6.000000,2000.000000,2004.000000,NaN,NaN,NaN,NaN,NaN,166.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,712.000000,NaN,0.000000,808.000000,1298.500000,NaN,NaN,NaN,NaN,1391.500000,728.000000,0.000000,1777.500000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,NaN,7.000000,NaN,1.000000,NaN,2002.000000,NaN,2.000000,607.184977,NaN,NaN,NaN,180.335986,96.523486,66.237591,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,NaN,NaN,214000.000000
max,190.000000,NaN,313.000000,215245.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,9.000000,2010.000000,2010.000000,NaN,NaN,NaN,NaN,NaN,1600.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5644.000000,NaN,1474.000000,2336.000000,6110.000000,NaN,NaN,NaN,NaN,4692.000000,2065.000000,572.000000,5642.000000,3.000000,2.000000,3.000000,2.000000,8.000000,3.000000,NaN,14.000000,NaN,3.000000,NaN,2010.000000,NaN,4.000000,1147.488093,NaN,NaN,NaN,572.298709,255.362547,225.762714,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,NaN,NaN,755000.000000

Too many nulls, Now we will deal with the nulls in batch of 20 variables at a time.

In [41]:
prop.iloc[:,0:20].isnull().sum()

Building_Class         0
Zoning_Class           0
Lot_Extent           259
Lot_Size               0
Road_Type              0
Property_Shape         0
Land_Outline           0
Utility_Type           0
Lot_Configuration      0
Property_Slope         0
Neighborhood           0
Condition1             0
Condition2             0
House_Type             0
House_Design           0
Overall_Material       0
House_Condition        0
Construction_Year      0
Remodel_Year           0
Roof_Design            0
dtype: int64

In [42]:
prop.iloc[:,20:50].isnull().sum()

Roof_Quality                  0
Exterior1st                   0
Exterior2nd                   0
Brick_Veneer_Type             8
Brick_Veneer_Area             8
Exterior_Material             0
Exterior_Condition            0
Foundation_Type               0
Basement_Height              37
Basement_Condition           37
Exposure_Level               38
BsmtFinType1                 37
BsmtFinSF1                    0
BsmtFinType2                 38
BsmtFinSF2                    0
BsmtUnfSF                     0
Total_Basement_Area           0
Heating_Type                  0
Heating_Quality               0
Air_Conditioning              0
Electrical_System             1
First_Floor_Area              0
Second_Floor_Area             0
LowQualFinSF                  0
Grade_Living_Area             0
Underground_Full_Bathroom     0
Underground_Half_Bathroom     0
Full_Bathroom_Above_Grade     0
Half_Bathroom_Above_Grade     0
Bedroom_Above_Grade           0
dtype: int64

In [43]:
prop.drop(['Lot_Extent',          
'Basement_Height',              
'Exposure_Level',               
'BsmtFinType2',                 
'Garage_Built_Year',          
'Garage_Finish_Year',         
'Garage_Condition' ],inplace=True,axis=1)

In [9]:
prop.shape

(1459, 68)

In [44]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [11]:
prop.isnull().sum()

Building_Class                0
Zoning_Class                  0
Lot_Size                      0
Road_Type                     0
Property_Shape                0
Land_Outline                  0
Utility_Type                  0
Lot_Configuration             0
Property_Slope                0
Neighborhood                  0
Condition1                    0
Condition2                    0
House_Type                    0
House_Design                  0
Overall_Material              0
House_Condition               0
Construction_Year             0
Remodel_Year                  0
Roof_Design                   0
Roof_Quality                  0
Exterior1st                   0
Exterior2nd                   0
Brick_Veneer_Type             8
Brick_Veneer_Area             8
Exterior_Material             0
Exterior_Condition            0
Foundation_Type               0
Basement_Condition           37
BsmtFinType1                 37
BsmtFinSF1                    0
BsmtFinSF2                    0
BsmtUnfSF                     0
Total_Basement_Area           0
Heating_Type                  0
Heating_Quality               0
Air_Conditioning              0
Electrical_System             1
First_Floor_Area              0
Second_Floor_Area             0
LowQualFinSF                  0
Grade_Living_Area             0
Underground_Full_Bathroom     0
Underground_Half_Bathroom     0
Full_Bathroom_Above_Grade     0
Half_Bathroom_Above_Grade     0
Bedroom_Above_Grade           0
Kitchen_Above_Grade           0
Kitchen_Quality               0
Rooms_Above_Grade             0
Functional_Rate               0
Fireplaces                    0
Garage                       81
Garage_Size                   0
Garage_Area                   0
Garage_Quality               81
Pavedd_Drive                  0
W_Deck_Area                   0
Open_Lobby_Area               0
Enclosed_Lobby_Area           0
Three_Season_Lobby_Area       0
Screen_Lobby_Area             0
Pool_Area                     0
Miscellaneous_Value           0
Month_Sold                    0
Year_Sold                     0
Sale_Type                     0
Sale_Condition                0
Sale_Price                    0
dtype: int64

In [12]:
prop.describe(include='all')

,Building_Class,Zoning_Class,Lot_Size,Road_Type,Property_Shape,Land_Outline,Utility_Type,Lot_Configuration,Property_Slope,Neighborhood,Condition1,Condition2,House_Type,House_Design,Overall_Material,House_Condition,Construction_Year,Remodel_Year,Roof_Design,Roof_Quality,Exterior1st,Exterior2nd,Brick_Veneer_Type,Brick_Veneer_Area,Exterior_Material,Exterior_Condition,Foundation_Type,Basement_Condition,BsmtFinType1,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,Total_Basement_Area,Heating_Type,Heating_Quality,Air_Conditioning,Electrical_System,First_Floor_Area,Second_Floor_Area,LowQualFinSF,Grade_Living_Area,Underground_Full_Bathroom,Underground_Half_Bathroom,Full_Bathroom_Above_Grade,Half_Bathroom_Above_Grade,Bedroom_Above_Grade,Kitchen_Above_Grade,Kitchen_Quality,Rooms_Above_Grade,Functional_Rate,Fireplaces,Garage,Garage_Size,Garage_Area,Garage_Quality,Pavedd_Drive,W_Deck_Area,Open_Lobby_Area,Enclosed_Lobby_Area,Three_Season_Lobby_Area,Screen_Lobby_Area,Pool_Area,Miscellaneous_Value,Month_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price
count,1459.000000,1459,1459.000000,1459,1459,1459,1459,1459,1459,1459,1459,1459,1459,1459,1459.000000,1459.000000,1459.000000,1459.000000,1459,1459,1459,1459,1451,1451.00000,1459,1459,1459,1422,1422,1459.000000,1459.000000,1459.000000,1459.000000,1459,1459,1459,1458,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459,1459.000000,1459,1459.000000,1378,1459.000000,1459.000000,1378,1459,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459,1459,1459.000000
unique,NaN,5,NaN,2,4,4,2,5,3,25,9,8,5,8,NaN,NaN,NaN,NaN,6,8,15,16,4,NaN,4,5,6,4,6,NaN,NaN,NaN,NaN,6,5,2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,8,NaN,7,NaN,NaN,5,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,6,NaN
top,NaN,RLD,NaN,Paved,Reg,Lvl,AllPub,I,GS,NAmes,Norm,Norm,1Fam,1Story,NaN,NaN,NaN,NaN,Gable,SS,VinylSd,VinylSd,None,NaN,TA,TA,PC,TA,Unf,NaN,NaN,NaN,NaN,GasA,Ex,Y,SBrkr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TA,NaN,TF,NaN,Attchd,NaN,NaN,TA,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WD,Normal,NaN
freq,NaN,1150,NaN,1453,924,1310,1458,1051,1381,225,1259,1444,1219,725,NaN,NaN,NaN,NaN,1140,1433,515,504,863,NaN,906,1281,647,1310,430,NaN,NaN,NaN,NaN,1427,741,1364,1333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,734,NaN,1359,NaN,869,NaN,NaN,1310,1339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1266,1197,NaN
mean,56.922550,NaN,10517.225497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.100069,5.575051,1971.272104,1984.879369,NaN,NaN,NaN,NaN,NaN,103.75672,NaN,NaN,NaN,NaN,NaN,443.374914,46.382454,567.535984,1057.293352,NaN,NaN,NaN,NaN,1162.562714,347.230295,5.848526,1515.641535,0.424949,0.057574,1.565456,0.382454,2.866347,1.046607,NaN,6.518163,NaN,0.613434,NaN,1.767649,470.934787,NaN,NaN,93.015667,47.811902,24.580227,3.411926,15.071282,2.760795,43.518849,6.322138,2007.815627,NaN,NaN,180944.102810
std,42.304033,NaN,9984.675721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.383171,1.113125,30.212814,20.645927,NaN,NaN,NaN,NaN,NaN,181.10815,NaN,NaN,NaN,NaN,NaN,456.142186,161.248500,441.874057,438.824912,NaN,NaN,NaN,NaN,386.712553,436.583480,48.639512,525.616607,0.518870,0.238830,0.550906,0.502798,0.816050,0.220410,NaN,1.625894,NaN,0.644687,NaN,0.747301,210.668787,NaN,NaN,124.796682,67.467586,61.353507,29.327247,55.775138,40.191018,496.291826,2.704540,1.328542,NaN,NaN,79464.918335
min,20.000000,NaN,1300.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1872.000000,1950.000000,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,2.000000,NaN,0.000000,NaN,0.000000,-129.369350,NaN,NaN,-338.112031,-187.149958,-164.807386,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,NaN,NaN,34900.000000
25%,20.000000,NaN,7549.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,5.000000,1954.000000,1967.000000,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,223.500000,795.500000,NaN,NaN,NaN,NaN,882.000000,0.000000,0.000000,1129.000000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,NaN,5.000000,NaN,0.000000,NaN,1.000000,329.290489,NaN,NaN,9.656026,1.843186,-16.807302,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,NaN,NaN,129950.000000
50%,50.000000,NaN,9477.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,5.000000,1973.000000,1994.000000,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,383.000000,0.000000,479.000000,991.000000,NaN,NaN,NaN,NaN,1086.000000,0.000000,0.000000,1464.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,NaN,6.000000,NaN,1.000000,NaN,2.000000,471.028116,NaN,NaN,92.803628,46.837919,25.026953,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,NaN,NaN,163000.000000
75%,70.000000,NaN,11603.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,6.000000,2000.000000,2004.000000,NaN,NaN,NaN,NaN,NaN,166.00000,NaN,NaN,NaN,NaN,NaN,712.000000,0.000000,808.000000,1298.500000,NaN,NaN,NaN,NaN,1391.500000,728.000000,0.000000,1777.500000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,NaN,7.000000,NaN,1.000000,NaN,2.000000,607.184977,NaN,NaN,180.335986,96.523486,66.237591,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,NaN,NaN,214000.000000
max,190.000000,NaN,215245.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,9.000000,2010.000000,2010.000000,NaN,NaN,NaN,NaN,NaN,1600.00000,NaN,NaN,NaN,NaN,NaN,5644.000000,1474.000000,2336.000000,6110.000000,NaN,NaN,NaN,NaN,4692.000000,2065.000000,572.000000,5642.000000,3.000000,2.000000,3.000000,2.000000,8.000000,3.000000,NaN,14.000000,NaN,3.000000,NaN,4.000000,1147.488093,NaN,NaN,572.298709,255.362547,225.762714,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,NaN,NaN,755000.000000

In [45]:
prop.Basement_Condition=prop.Basement_Condition.fillna('TA')
prop.BsmtFinType1=prop.BsmtFinType1.fillna('Unf')
prop.Garage=prop.Garage.fillna('Attchd')
prop.Garage_Quality=prop.Garage_Quality.fillna('TA')

In [46]:
prop.isnull().sum()

Building_Class               0
Zoning_Class                 0
Lot_Size                     0
Road_Type                    0
Property_Shape               0
Land_Outline                 0
Utility_Type                 0
Lot_Configuration            0
Property_Slope               0
Neighborhood                 0
Condition1                   0
Condition2                   0
House_Type                   0
House_Design                 0
Overall_Material             0
House_Condition              0
Construction_Year            0
Remodel_Year                 0
Roof_Design                  0
Roof_Quality                 0
Exterior1st                  0
Exterior2nd                  0
Brick_Veneer_Type            8
Brick_Veneer_Area            8
Exterior_Material            0
Exterior_Condition           0
Foundation_Type              0
Basement_Condition           0
BsmtFinType1                 0
BsmtFinSF1                   0
BsmtFinSF2                   0
BsmtUnfSF                    0
Total_Basement_Area          0
Heating_Type                 0
Heating_Quality              0
Air_Conditioning             0
Electrical_System            1
First_Floor_Area             0
Second_Floor_Area            0
LowQualFinSF                 0
Grade_Living_Area            0
Underground_Full_Bathroom    0
Underground_Half_Bathroom    0
Full_Bathroom_Above_Grade    0
Half_Bathroom_Above_Grade    0
Bedroom_Above_Grade          0
Kitchen_Above_Grade          0
Kitchen_Quality              0
Rooms_Above_Grade            0
Functional_Rate              0
Fireplaces                   0
Garage                       0
Garage_Size                  0
Garage_Area                  0
Garage_Quality               0
Pavedd_Drive                 0
W_Deck_Area                  0
Open_Lobby_Area              0
Enclosed_Lobby_Area          0
Three_Season_Lobby_Area      0
Screen_Lobby_Area            0
Pool_Area                    0
Miscellaneous_Value          0
Month_Sold                   0
Year_Sold                    0
Sale_Type                    0
Sale_Condition               0
Sale_Price                   0
dtype: int64

In [15]:
prop.shape

(1459, 68)

In [47]:
prop.dropna(inplace=True)

In [17]:
prop.shape

(1450, 68)

Now that the data is cleaned, we will convert the object variables into numerical ones.

In [48]:
import sklearn
from sklearn.preprocessing  import LabelEncoder
le=LabelEncoder()

In [49]:
x=prop
for i in range(1,x.shape[1]):
    if x.dtypes[i]=='object':
        x[x.columns[i]]=le.fit_transform(x[x.columns[i]])

In [50]:
prop.describe(include='all')

,Building_Class,Zoning_Class,Lot_Size,Road_Type,Property_Shape,Land_Outline,Utility_Type,Lot_Configuration,Property_Slope,Neighborhood,Condition1,Condition2,House_Type,House_Design,Overall_Material,House_Condition,Construction_Year,Remodel_Year,Roof_Design,Roof_Quality,Exterior1st,Exterior2nd,Brick_Veneer_Type,Brick_Veneer_Area,Exterior_Material,Exterior_Condition,Foundation_Type,Basement_Condition,BsmtFinType1,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,Total_Basement_Area,Heating_Type,Heating_Quality,Air_Conditioning,Electrical_System,First_Floor_Area,Second_Floor_Area,LowQualFinSF,Grade_Living_Area,Underground_Full_Bathroom,Underground_Half_Bathroom,Full_Bathroom_Above_Grade,Half_Bathroom_Above_Grade,Bedroom_Above_Grade,Kitchen_Above_Grade,Kitchen_Quality,Rooms_Above_Grade,Functional_Rate,Fireplaces,Garage,Garage_Size,Garage_Area,Garage_Quality,Pavedd_Drive,W_Deck_Area,Open_Lobby_Area,Enclosed_Lobby_Area,Three_Season_Lobby_Area,Screen_Lobby_Area,Pool_Area,Miscellaneous_Value,Month_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price
count,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.00000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000,1450.000000
mean,56.958621,3.033103,10508.202069,0.995862,1.939310,2.775862,0.000690,3.017241,0.062759,12.233793,2.031724,2.008276,0.493793,3.035862,6.094483,5.579310,1971.096552,1984.773793,1.411724,4.020000,9.621379,10.338621,1.760690,103.828276,2.544138,3.731724,1.405517,2.817241,2.788276,442.007586,46.670345,567.494483,1056.172414,1.036552,1.543448,0.934483,3.68000,1161.486207,346.981379,5.884828,1514.352414,0.423448,0.057931,1.562759,0.380690,2.866897,1.046207,2.342069,6.517241,6.649655,0.613103,3.210345,1.765517,470.284364,3.871034,1.855172,92.812863,47.745863,24.728779,3.433103,15.164828,2.777931,43.788966,6.319310,2007.815172,7.513793,3.768276,180646.946207
std,42.353857,0.627422,9996.423467,0.064216,1.409976,0.709861,0.026261,1.623790,0.277135,6.002515,0.871503,0.259931,1.198240,1.911813,1.381644,1.113745,30.200257,20.651932,0.836207,0.281007,3.197775,3.541213,0.616071,181.150114,0.691901,0.733992,0.758461,0.651255,1.839675,455.412411,161.706929,442.216597,438.034259,0.296125,1.740946,0.247522,1.05459,385.127362,436.508758,48.788142,525.937165,0.518800,0.239527,0.550293,0.502485,0.815359,0.219643,0.830049,1.627080,1.346730,0.643463,1.768688,0.748717,210.545584,0.596102,0.498158,124.845882,67.582725,61.116448,29.416948,55.935396,40.315051,497.818831,2.701271,1.329826,1.555556,1.102147,79334.716002
min,20.000000,0.000000,1300.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,-129.369350,0.000000,0.000000,-338.112031,-187.149958,-164.807386,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,0.000000,0.000000,34900.000000
25%,20.000000,3.000000,7536.250000,1.000000,0.000000,3.000000,0.000000,2.000000,0.000000,7.000000,2.000000,2.000000,0.000000,2.000000,5.000000,5.000000,1954.000000,1966.250000,1.000000,4.000000,8.000000,8.000000,1.000000,0.000000,2.000000,4.000000,1.000000,3.000000,1.000000,0.000000,0.000000,223.000000,795.000000,1.000000,0.000000,1.000000,4.00000,882.000000,0.000000,0.000000,1128.000000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,2.000000,5.000000,7.000000,0.000000,2.000000,1.000000,329.028875,4.000000,2.000000,9.614488,1.761310,-16.545537,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,8.000000,4.000000,129900.000000
50%,50.000000,3.000000,9470.500000,1.000000,3.000000,3.000000,0.000000,4.000000,0.000000,12.000000,2.000000,2.000000,0.000000,2.000000,6.000000,5.000000,1972.000000,1993.000000,1.000000,4.000000,12.000000,13.000000,2.000000,0.000000,3.000000,4.000000,1.000000,3.000000,2.000000,381.000000,0.000000,479.500000,990.500000,1.000000,0.000000,1.000000,4.00000,1086.000000,0.000000,0.000000,1464.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,3.000000,6.000000,7.000000,1.000000,2.000000,2.000000,470.641515,4.000000,2.000000,92.723220,46.037053,25.251045,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,8.000000,4.000000,162700.000000
75%,70.000000,3.000000,11600.000000,1.000000,3.000000,3.000000,0.000000,4.000000,0.000000,17.000000,2.000000,2.000000,0.000000,5.000000,7.000000,6.000000,2000.000000,2004.000000,1.000000,4.000000,12.000000,13.000000,2.000000,166.000000,3.000000,4.000000,2.000000,3.000000,5.000000,706.000000,0.000000,808.000000,1297.750000,1.000000,4.000000,1.000000,4.00000,1391.000000,728.000000,0.000000,1776.000000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,3.000000,7.000000,7.000000,1.000000,6.000000,2.000000,607.047742,4.000000,2.000000,180.066776,96.574684,66.107842,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,8.000000,4.000000,214000.000000
max,190.000000,4.000000,215245.000000,1.000000,3.000000,3.000000,1.000000,4.000000,2.000000,24.000000,8.000000,7.000000,4.000000,7.000000,10.000000,9.000000,2010.000000,2010.000000,5.000000,7.000000,14.000000,15.000000,3.000000,1600.000000,3.000000,4.000000,5.000000,3.000000,5.000000,5644.000000,1474.000000,2336.000000,6110.000000,5.000000,4.000000,1.000000,4.00000,4692.000000,2065.000000,572.000000,5642.000000,3.000000,2.000000,3.000000,2.000000,8.000000,3.000000,3.000000,14.000000,7.000000,3.000000,6.000000,4.000000,1147.488093,4.000000,2.000000,572.298709,255.362547,225.762714,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,8.000000,5.000000,755000.000000

In [21]:
prop.shape

(1450, 68)

The real task begins from here, we will split the data into x and y for preparing to create a model.

In [51]:
prop_x=prop.iloc[:,0:67]
prop_y=prop.iloc[:,-1]

In [52]:
prop_y.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: Sale_Price, dtype: int64

In [53]:
from sklearn.model_selection import train_test_split
prop_x_train,prop_x_test,prop_y_train,prop_y_test=train_test_split(prop_x,prop_y,test_size=.2,random_state=101)

In [54]:
from sklearn import linear_model
reg=linear_model.LinearRegression()

In [55]:
reg.fit(prop_x_train,prop_y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [56]:
prop_rsq=reg.score(prop_x_train,prop_y_train)
prop_rsq

0.845624106380255

In [57]:
prop_adjrsq=1-(((1-prop_rsq)*((prop_x_train.shape[0]-1)))/((prop_x_train.shape[0])-prop_x_train.shape[1]-1))
prop_adjrsq

0.8361523253614611

We have got adjusted r square of around 83%

In [58]:
prop_predict=reg.predict(prop_x_test)

In [59]:
from sklearn import metrics

In [60]:
prop_mse=metrics.mean_squared_error(prop_y_test,prop_predict)
prop_mse

1495278489.6203802

In [61]:
prop_mae=metrics.median_absolute_error(prop_y_test,prop_predict)
prop_mae

13939.931281272613

In [62]:
import numpy as np

In [63]:
prop_rmse=np.sqrt(prop_mse)
prop_rmse

38668.830983369284

In [64]:
error=prop_y_test-prop_predict
per_err=error/prop_y_test
abs_err=np.absolute(per_err)
prop_mape=np.mean(abs_err)
prop_mape

0.10882341383374448

Error Percentage in our model is around 10%.